all: 01_access 02_gets 03_rwx_mem 04_memcpy 04_strncpy 04_strcpy 05_security_file_open 06_sprintf 07_snprintf 08_printf_mutability 09_system_mutability 10_system_abs 11_filep_unlocked 12_fixed_mmap 13_interceptable_path

clean:
	rm 01_access 02_gets 03_rwx_mem 04_memcpy 04_strncpy 04_strcpy 05_security_file_open 06_sprintf 07_snprintf 08_printf_mutability 09_system_mutability 10_system_abs 11_filep_unlocked 12_fixed_mmap 13_interceptable_path

01_access: 01_access.c
	gcc 01_access.c -o 01_access

02_gets: 02_gets.c
	gcc 02_gets.c -o 02_gets

03_rwx_mem: 03_rwx_mem.c
	gcc 03_rwx_mem.c -o 03_rwx_mem

04_memcpy: 04_memcpy.c
	gcc 04_memcpy.c -o 04_memcpy

04_strncpy: 04_strncpy.c
	gcc 04_strncpy.c -o 04_strncpy

04_strcpy: 04_strcpy.c
	gcc 04_strcpy.c -o 04_strcpy

05_security_file_open: 05_security_file_open.c
	gcc 05_security_file_open.c -o 05_security_file_open

06_sprintf: 06_sprintf.c
	gcc 06_sprintf.c -o 06_sprintf

07_snprintf: 07_snprintf.c
	gcc 07_snprintf.c -o 07_snprintf

08_printf_mutability: 08_printf_mutability.c
	gcc 08_printf_mutability.c -o 08_printf_mutability

09_system_mutability: 09_system_mutability.c
	gcc 09_system_mutability.c -o 09_system_mutability

10_system_abs: 10_system_abs.c
	gcc 10_system_abs.c -o 10_system_abs

11_filep_unlocked: 11_filep_unlocked.c
	gcc 11_filep_unlocked.c -o 11_filep_unlocked

12_fixed_mmap: 12_fixed_mmap.c
	gcc 12_fixed_mmap.c -o 12_fixed_mmap

13_interceptable_path: 13_interceptable_path.c
	gcc 13_interceptable_path.c -o 13_interceptable_path
